### ISSUE TITLE
When using parenthesis in a regex pattern, then the field is rendered as a method in plantuml diagram

### ISSUE THREAD

**Issue by armand-janssen** [armand-janssen/openapi-transformer#15]
When PlantUML sees parenthesis, it assumes it is a method instead of a field.
You can prepend this file with {field} to override this.

OpenAPI Schema

```
components:
  schemas:
    someClass:
      type: Object
      properties:
        someField:
          type: string
          maxLength: 100
        problemField:
          type: string
          pattern: '^(NL|nl)([0-9]){5}$'
        someOtherField:
          type: string
          maxLength: 100
```

Generated PlantUML
```
@startuml
class someClass {
  someField : string [maxLength : 100]
  problemField : string [pattern : ^(NL|nl)([0-9]){5}$ ]
  someOtherField : string [maxLength : 100]
}

@enduml
```

Solution PlantUML

```
@startuml
class someClass {
  someField : string [maxLength : 100]
  {field} problemField : string [pattern : ^(NL|nl)([0-9]){5}$ ]
  someOtherField : string [maxLength : 100]
}
@enduml
```
